- block:

  - name: homebrew cask packages install
    homebrew_cask:
      name={{ item.name }}
      state=present
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: '{{ packages }}'
